name: Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docs:
    uses: li0ard/workflow/.github/workflows/docs.yml@011b6c3387ee28ccb17fc6b849a4d117ab12472b
    with:
      deploy: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'li0ard/tsemrtd' }}
    permissions:
      contents: read
      pages: write
      id-token: write