name: Publish (JSR)
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # idk why i do this, but sometimes it doesnt work without it.
      - name: Install dependencies
        run: bun i

      - name: Publish package
        run: bunx --bun jsr publish