name: Tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md' # ignore changes to readmes
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: test
    uses: li0ard/workflow/.github/workflows/test.yml@011b6c3387ee28ccb17fc6b849a4d117ab12472b