name: Tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md' # ignore changes to readmes
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun i
      - run: bun test